feat(squash): packaging system updates

diff --git a/dist/collect_coverage b/dist/collect_coverage
--- a/dist/collect_coverage
+++ b/dist/collect_coverage
@@ -7,7 +7,30 @@ set -eo pipefail
 
 TEST_RUNNER="${TEST_RUNNER-"t"}"
 
-main() {
+_cc_external_dependencies_array=("kcov")
+
+_cc_check_arguments() {
+  if [[ -z "${1}" ]] || [[ "${#@}" != "1" ]]; then
+    echo "ERROR: You must supply a single argument as the target path."
+    return 127
+  fi
+}
+
+_cc_check_external_dependencies() {
+  local required_file
+
+  for required_file in "${_cc_external_dependencies_array[@]}"; do
+    if ! command -v "${required_file}" > /dev/null; then
+      echo "ERROR: the required external dependency '${required_file}' was not found in PATH !"
+      exit 127
+    fi
+  done
+}
+
+_cc_main() {
+  _cc_check_arguments "${@}"
+  _cc_check_external_dependencies
+
   [[ -d coverage ]] && rm -r coverage
 
   kcov \
@@ -27,4 +50,4 @@ main() {
   return 127
 }
 
-main "${@}"
+_cc_main "${@}"
diff --git a/dist/t b/dist/t
--- a/dist/t
+++ b/dist/t
@@ -5,6 +5,37 @@
 
 set -eo pipefail
 
+_t_runner_external_dependencies_array=("bash_unit")
+_t_runner_external_dependencies_notes=("Please see: https://github.com/bash-unit/bash_unit")
+_t_runner_stdlib_distributable_files_array=("stdlib.sh" "stdlib_testing.sh")
+
+_t_runner_check_external_dependencies() {
+  local required_file
+  local required_file_notes
+  local index
+
+  for ((index = 0; index < "${#_t_runner_external_dependencies_array[@]}"; ++index)); do
+    required_file="${_t_runner_external_dependencies_array[index]}"
+    required_file_notes="${_t_runner_external_dependencies_notes[index]}"
+    if ! command -v "${required_file}" > /dev/null; then
+      echo "ERROR: the required external dependency '${required_file}' was not found in PATH !"
+      echo "${required_file_notes}"
+      exit 127
+    fi
+  done
+}
+
+_t_runner_check_stdlib() {
+  local required_file
+
+  for required_file in "${_t_runner_stdlib_distributable_files_array[@]}"; do
+    if [[ ! -f "${_t_runner_working_directory}/${required_file}" ]]; then
+      echo "ERROR: the stdlib distributable file '${required_file}' was not found in the same directory as the test runner script !"
+      exit 127
+    fi
+  done
+}
+
 _t_runner_discover() {
   # $1: a filter to match tests by
 
@@ -26,13 +57,15 @@ _t_runner_execute() {
   set +e
   (
     # shellcheck source=/dev/null
-    source /usr/local/bin/bash_unit -p "${1}" "${_t_runner_discovered_test_modules[@]}"
+    source "$(command -v bash_unit)" -p "${1}" "${_t_runner_discovered_test_modules[@]}"
   )
   _t_runner_exit_code="$?"
   set -e
 }
 
 _t_runner_execution_context() {
+  _t_runner_check_stdlib
+
   # shellcheck source=/dev/null
   source "${_t_runner_working_directory}/stdlib.sh"
   # shellcheck source=/dev/null
@@ -51,6 +84,8 @@ _t_runner_main() {
   local _t_runner_working_directory
 
   _t_runner_working_directory="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &> /dev/null && pwd)"
+
+  _t_runner_check_external_dependencies
 
   _t_runner_discover "${1-.}"
 
